# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 'Reproducible Data Science + Python + Real-World Data'
author: Valentin Danchev
logo: mylogo2.png
copyright: 2021
page_titles: false
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/valdanchev/reproducible-data-science-python  # Online location of your book
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url: "https://mybinder.org/v2/gh/valdanchev/reproducible-data-science-python/31c38357d5c7984962694637cf1a5f9a1bcf1f40"  # The URL for your BinderHub (e.g., https://mybinder.org)
  
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
#  home_page_in_navbar: false
